---

name: CI
on:
    push:
        branches:
            - main
    pull_request: null
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [16.x, 18.x, 20.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install
              run: npm install
            - name: Lint
              run: npm run lint
            - name: Test
              run: npm test
